export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import Navbar from"./navbar"
export default function RootLayout({ children }) {
 return (
    <html lang="en">
   
      <body>
      {/* <Navbar/> */}
        {children}
        </body>
    </html>
  )
}
